// Custom Cloudflare Worker entry point.
//
// It wraps the Astro + @astrojs/cloudflare server build (dist/server/entry.mjs)
// so we can enforce canonical-domain redirects at the edge BEFORE the request
// reaches the app:
//   1. http://  -> https://   (301)   — also covered by Cloudflare "Always Use HTTPS"
//   2. www.    -> apex         (301)   — Workers static assets can't do domain-level
//                                      redirects via _redirects, so we do it here.
// Everything else delegates to the Astro SSR handler (which falls back to ASSETS).

// @ts-nocheck — dist/server/entry.mjs is generated by `astro build` and not
// present during editor type-checking; wrangler bundles this worker at deploy.
import astroHandler from '../dist/server/entry.mjs';

const APEX_HOST = 'kaohsiungcentralpark.com';

export default {
  async fetch(request: Request, env: Record<string, unknown>, ctx: unknown): Promise<Response> {
    const url = new URL(request.url);

    // 1) Force HTTPS.
    if (url.protocol === 'http:') {
      url.protocol = 'https:';
      return Response.redirect(url.toString(), 301);
    }

    // 2) Strip www. and redirect to the canonical apex domain.
    if (url.hostname.toLowerCase().startsWith('www.')) {
      url.hostname = APEX_HOST;
      return Response.redirect(url.toString(), 301);
    }

    // Delegate to the Astro SSR handler (passes through env/ctx for ASSETS, etc.).
    return astroHandler.fetch(request, env, ctx);
  },
};
